plugins:
  - jekyll-relative-links
theme: cayman
relative_links:
  enabled: true
  collections: true
include:
    - test.md
  # - CONTRIBUTING.md
  # - README.md
  # - LICENSE.md
  # - COPYING.md
  # - CODE_OF_CONDUCT.md
  # - CONTRIBUTING.md
  # - ISSUE_TEMPLATE.md
  # - PULL_REQUEST_TEMPLATE.md
